grails-app/domain/randseat/Paper.groovy
package randseat

class Paper {

    String name
    String extName
    boolean inUse=true

    static belongsTo = [exam: Exam]

    static hasMany = [students:Student]

    static constraints = {
        exam nullable: false
        name nullable: false
        extName nullable: false
        inUse nullable: false
        students nullable: true
    }

    static mapping = {
        exam comment: '考试'
        name comment: '试卷名称'
        extName comment: '外部名称'
        inUse comment: '是否使用'
        students comment: '该考卷的学生'
    }

    @Override
    public String toString() {
        return name+"("+extName+")"
    }
}

grails-app/controllers/randseat/PaperController.groovy
package randseat

import grails.converters.JSON
import org.springframework.dao.DataIntegrityViolationException

class PaperController {

    def grailsUiExtensions

    static allowedMethods = [save: "POST", update: "POST", delete: "POST", addPaper: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params['max'] = Math.min(max ?: 10, 100)
        params['sort'] = 'id'
        params['order']= 'desc'
        [paperInstanceList: Paper.list(params), paperInstanceTotal: Paper.count(), params: params]
    }

    def create() {
        [paperInstance: new Paper(params)]
    }

    def save() {
        def paperInstance = new Paper(params)
        if (!paperInstance.save(flush: true)) {
            render(view: "create", model: [paperInstance: paperInstance])
            return
        }

        grailsUiExtensions.displayFlashMessage(text: 'default.created.message', args: [message(code: 'paper.label', default: 'Paper'), paperInstance])
        redirect(action: "show", controller: "exam", id: paperInstance.id)
    }

    def show(Long id) {
        def paperInstance = Paper.get(id)
        if (!paperInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'paper.label', default: 'Paper'), id])
            redirect(action: "list")
            return
        }

        [paperInstance: paperInstance]
    }

    def edit(Long id) {
        def paperInstance = Paper.get(id)
        if (!paperInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'paper.label', default: 'Paper'), id])
            redirect(action: "list")
            return
        }

        [paperInstance: paperInstance]
    }

    def update(Long id, Long version) {
        def paperInstance = Paper.get(id)
        if (!paperInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'paper.label', default: 'Paper'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (paperInstance.version > version) {
                    paperInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                            [message(code: 'paper.label', default: 'Paper')] as Object[],
                            "Another user has updated this Paper while you were editing")
                render(view: "edit", model: [paperInstance: paperInstance])
                return
            }
        }

        bindData(paperInstance, params)

        if (!paperInstance.save(flush: true)) {
            render(view: "edit", model: [paperInstance: paperInstance])
            return
        }

        grailsUiExtensions.displayFlashMessage(text: 'default.updated.message', args: [message(code: 'paper.label', default: 'Paper'), paperInstance])
        redirect(action: "show", controller: "exam", id: paperInstance.exam.id)
    }

    def delete(Long id) {
        def paperInstance = Paper.get(id)
        if (!paperInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'paper.label', default: 'Paper'), id])
            redirect(action: "list")
            return
        }

        try {
            paperInstance.delete(flush: true)
            redirect(action: "show", controller: "exam", id: paperInstance.exam.id)
        }
        catch (DataIntegrityViolationException e) {
            grailsUiExtensions.displayFlashMessage(type: 'error', text: 'default.not.deleted.message', args: [message(code: 'paper.label', default: 'Paper'), paperInstance])
            redirect(action: "show", id: id)
        }
    }

    /**
     * for ajax
     */
    def addPaper(){
        def res=[:]
        def data=[:]

        def examInstance = Exam.findById(params.getInt('exam'))
        def name = params['name']
        def extName = params['extName']
        if (!examInstance) {
            res['message']='找不到该考试'
            data['code']=0
            data['res']=res
            render data as JSON
            return false
        }
        if (!name || !extName){
            res['message']='考卷名称和外部名称不能为空'
            data['code']=0
            data['res']=res
            render data as JSON
            return false
        }
        def paperInstance = new Paper()
        paperInstance.exam = examInstance
        paperInstance.name = name
        paperInstance.extName = extName
        paperInstance.inUse = true
        paperInstance.save(failOnError: true,flush: true)

        res['message']='添加成功'
        data['code']=1
        data['res']=res
        render data as JSON
    }
}

grails-app/views/paper/_form.gsp
<%@ page import="randseat.Paper" %>



<div class="fieldcontain ${hasErrors(bean: paperInstance, field: 'exam', 'error')} required">
    <label for="exam">
        <g:message code="paper.exam.label" default="Exam"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="exam" name="exam.id" from="${randseat.Exam.list()}" optionKey="id" required="" value="${paperInstance?.exam?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: paperInstance, field: 'name', 'error')} required">
    <label for="name">
        <g:message code="paper.name.label" default="Name"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="name" required="" value="${paperInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: paperInstance, field: 'extName', 'error')} required">
    <label for="extName">
        <g:message code="paper.extName.label" default="Ext Name"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="extName" required="" value="${paperInstance?.extName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: paperInstance, field: 'inUse', 'error')} ">
    <label for="inUse">
        <g:message code="paper.inUse.label" default="In Use"/>
        
    </label>
    <g:checkBox name="inUse" value="${paperInstance?.inUse}" />

</div>

grails-app/views/paper/create.gsp
<%@ page import="randseat.Paper" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'paper.label', default: 'Paper')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <g:link class="btn">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </g:link>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="save" >
    <fieldset>
        <f:all bean="paperInstance" except="students"/>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.create.label" default="Create"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/paper/edit.gsp
<%@ page import="randseat.Paper" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'paper.label', default: 'Paper')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="update" id="${paperInstance?.id}" >
    <g:hiddenField name="version" value="${paperInstance?.version}"/>
    <fieldset>
        <f:all bean="paperInstance" except="students"/>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.update.label" default="Update"/>
        </ui:button>
        <ui:button type="submit" mode="danger" name="_action_delete" formnovalidate="true" id="delete-button">
            <i class="icon-trash icon-white"></i>
            <g:message code="default.button.delete.label" default="Delete"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/paper/index.gsp
<%@ page import="randseat.Paper" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'paper.label', default: 'Paper')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-paper" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-paper" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>
            
            <th><g:message code="paper.exam.label" default="Exam"/></th>
            
            <g:sortableColumn property="name"
                              title="${message(code: 'paper.name.label', default: 'Name')}"/>
            
            <g:sortableColumn property="extName"
                              title="${message(code: 'paper.extName.label', default: 'Ext Name')}"/>
            
            <g:sortableColumn property="inUse"
                              title="${message(code: 'paper.inUse.label', default: 'In Use')}"/>
            
        </tr>
        </thead>
        <tbody>
        <g:each in="${paperInstanceList}" status="i" var="paperInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                
                <td><g:link action="show" id="${paperInstance.id}">${fieldValue(bean: paperInstance, field: "exam")}</g:link></td>
                
                <td>${fieldValue(bean: paperInstance, field: "name")}</td>
                
                <td>${fieldValue(bean: paperInstance, field: "extName")}</td>
                
                <td><g:formatBoolean boolean="${paperInstance.inUse}"/></td>
                
            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${paperInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/paper/list.gsp
<%@ page import="randseat.Paper" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'paper.label', default: 'Paper')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <g:link action="create" class="btn btn-primary">
            <g:message code="default.button.create.label" default="Create"/>
        </g:link>
    </theme:zone>
    <ui:displayMessage/>
    <div id="flip-scroll">
        <ui:table class="table-bordered table-hover">
            <thead>
            <ui:tr>
                
                <g:sortableColumn property="id"
                                  title="${message(code: 'paper.id.label', default: 'Id')}" params="${params}"/>
                
                <th><g:message code="paper.exam.label" default="Exam"/></th>
                
                <g:sortableColumn property="name"
                                  title="${message(code: 'paper.name.label', default: 'Name')}" params="${params}"/>
                
                <g:sortableColumn property="extName"
                                  title="${message(code: 'paper.extName.label', default: 'Ext Name')}" params="${params}"/>
                
                <g:sortableColumn property="inUse"
                                  title="${message(code: 'paper.inUse.label', default: 'In Use')}" params="${params}"/>
                
                <th><g:message code="default.actions.label" default="Actions"/></th>
            </ui:tr>
            </thead>
            <tbody>
            <g:each in="${paperInstanceList}" var="paperInstance">
                <ui:tr>
                    
                    <td><f:display bean="${paperInstance}" property="id"/></td>
                    
                    <td><f:display bean="${paperInstance}" property="exam"/></td>
                    
                    <td><f:display bean="${paperInstance}" property="name"/></td>
                    
                    <td><f:display bean="${paperInstance}" property="extName"/></td>
                    
                    <td><g:formatBoolean boolean="${paperInstance.inUse}"/></td>
                    
                    <td class="link">
                        <ui:button kind="anchor" mode="info" class="btn-mini" action="show" id="${paperInstance.id}">
                            <i class="icon-info-sign"></i>
                            <g:message code="default.button.show.label" default="Show"/>
                        </ui:button>
                    </td>
                </ui:tr>
            </g:each>
            </tbody>
        </ui:table>
    </div>

    <div class="pagination">
        <ui:paginate total="${paperInstanceTotal}" params="${params}"/>
    </div>
</theme:zone>
</body>
</html>

grails-app/views/paper/show.gsp
<%@ page import="randseat.Paper" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'paper.label', default: 'Paper')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor" mode="primary" action="edit" id="${paperInstance?.id}">
            <i class="icon-pencil"></i>
            <g:message code="default.button.edit.label" default="Edit"/>
        </ui:button>
        <ui:form action="delete" class="inline">
            <g:hiddenField name="id" value="${paperInstance?.id}"/>
            <ui:button mode="danger" type="submit" name="_action_delete" id="delete-button">
                <i class="icon-trash icon-white"></i>
                <g:message code="default.button.delete.label" default="Delete"/>
            </ui:button>
        </ui:form>
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <dl>
        
        <g:if test="${paperInstance?.exam}">
            <dt><g:message code="paper.exam.label" default="Exam"/></dt>
            
            <dd><g:link controller="exam" action="show"
                        id="${paperInstance?.exam?.id}"><f:display bean="${paperInstance}"
                                                                           property="exam"/></g:link></dd>
            
        </g:if>
        
        <g:if test="${paperInstance?.name}">
            <dt><g:message code="paper.name.label" default="Name"/></dt>
            
            <dd><f:display bean="${paperInstance}" property="name"/></dd>
            
        </g:if>
        
        <g:if test="${paperInstance?.extName}">
            <dt><g:message code="paper.extName.label" default="Ext Name"/></dt>
            
            <dd><f:display bean="${paperInstance}" property="extName"/></dd>
            
        </g:if>
        
        <g:if test="${paperInstance?.inUse}">
            <dt><g:message code="paper.inUse.label" default="In Use"/></dt>
            
            <dd><g:formatBoolean boolean="${paperInstance?.inUse}"/></dd>
            
        </g:if>
        
    </dl>

</theme:zone>
</body>
</html>