grails-app/domain/randseat/Room.groovy
package randseat

class Room {

    String name
    String place
    String code
    Integer seatCount
    Integer width
    Integer height

    static hasMany = [ranges: Ranges,exams: ExamRoom,students:Student]

    static constraints = {
        name nullable: false
        place nullable: false
        code nullable: false
        seatCount nullable: false
        width nullable: false
        height nullable: false
        ranges nullable: true
        exams nullable: true
        students nullable: true
    }
    static mapping = {
        name comment: '考场名称'
        place comment: '考场地点'
        code comment: '考场编码'
        seatCount comment: '座位数'
        width comment: '考场宽座位数'
        height comment: '考场长座位数'
        ranges comment: '考场区域数'
        exams comment: '考场考试集合'
        students comment: '在该考场的学生'
    }

    @Override
    public String toString() {
        return name+"("+seatCount+")"
    }
}

grails-app/controllers/randseat/RoomController.groovy
package randseat

import org.springframework.dao.DataIntegrityViolationException

class RoomController {

    def grailsUiExtensions

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params['max'] = Math.min(max ?: 10, 100)
        [roomInstanceList: Room.list(params), roomInstanceTotal: Room.count(), params: params]
    }

    def create() {
        [roomInstance: new Room(params)]
    }

    def save() {
        def roomInstance = new Room(params)
        if (!roomInstance.save(flush: true)) {
            render(view: "create", model: [roomInstance: roomInstance])
            return
        }

        grailsUiExtensions.displayFlashMessage(text: 'default.created.message', args: [message(code: 'room.label', default: 'Room'), roomInstance])
        redirect(action: "show", id: roomInstance.id)
    }

    def show(Long id) {
        def roomInstance = Room.get(id)
        if (!roomInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'room.label', default: 'Room'), id])
            redirect(action: "list")
            return
        }

        [roomInstance: roomInstance]
    }

    def edit(Long id) {
        def roomInstance = Room.get(id)
        if (!roomInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'room.label', default: 'Room'), id])
            redirect(action: "list")
            return
        }

        [roomInstance: roomInstance]
    }

    def update(Long id, Long version) {
        def roomInstance = Room.get(id)
        if (!roomInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'room.label', default: 'Room'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (roomInstance.version > version) {
                    roomInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                            [message(code: 'room.label', default: 'Room')] as Object[],
                            "Another user has updated this Room while you were editing")
                render(view: "edit", model: [roomInstance: roomInstance])
                return
            }
        }

        bindData(roomInstance, params)

        if (!roomInstance.save(flush: true)) {
            render(view: "edit", model: [roomInstance: roomInstance])
            return
        }

        grailsUiExtensions.displayFlashMessage(text: 'default.updated.message', args: [message(code: 'room.label', default: 'Room'), roomInstance])
        redirect(action: "show", id: roomInstance.id)
    }

    def delete(Long id) {
        def roomInstance = Room.get(id)
        if (!roomInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'room.label', default: 'Room'), id])
            redirect(action: "list")
            return
        }

        try {
            roomInstance.delete(flush: true)
            grailsUiExtensions.displayFlashMessage(text: 'default.deleted.message', args: [message(code: 'room.label', default: 'Room'), roomInstance])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            grailsUiExtensions.displayFlashMessage(type: 'error', text: 'default.not.deleted.message', args: [message(code: 'room.label', default: 'Room'), roomInstance])
            redirect(action: "show", id: id)
        }
    }

    def showSeatMap(Long id){
        def roomInstance = Room.get(id)
        if (!roomInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'room.label', default: 'Room'), id])
            redirect(action: "list")
            return
        }

        String[][] seatMap = new String[roomInstance.width+1][roomInstance.height+1]
        def rangesInstanceList = Ranges.findAllByRoom(roomInstance,[sort: "seq", order: "desc"])
        if (rangesInstanceList){
            rangesInstanceList.each {ranges ->
                def seatInstanceList = Seat.findAllByRange(ranges)
                if (seatInstanceList){
                    seatInstanceList.each {seat ->
                        def usable = seat.usable?1:0
                        seatMap[seat.col][seat.row]=[seat.id,seat.code,usable].join(":")
                    }
                }
            }
        }

        // 根据区域数组生成html
        StringBuilder sb = new StringBuilder()
        sb.append("")
        sb.append("<table>")
        for (int col = 0; col <=roomInstance.width ; col++) {
            sb.append("<tr>")
            for (int row = 1; row < roomInstance.height+1; row++) {
                sb.append("<td align='center'>")
                if (seatMap[col][row]){
                    def attr = seatMap[col][row].split(":") // [seat.id,seat.code,usable]
                    def seatId = attr[0].toInteger()
                    def seatCode = attr[1].toInteger()
                    def seatUsable = attr[2].toInteger()
                    if (seatUsable){
//                        sb.append("${g:link(action: 'show',controller: 'seat',class: 'btn btn-info btn-mini btn-block btn-app no-radius',style: 'height:80px;width:80px',id: seatId)}")
                        sb.append("<a href=\"/randseat/seat/show/${seatId}\" style='height:80px;width:80px' align='bottom' class='btn btn-info btn-mini btn-block btn-app no-radius' data-original-title='可用' data-rel='tooltip' data-placement='right' id='seatId_${seatId}' name='seatId_${seatId}'>")
                        sb.append("<span class=\"badge badge-yellow\">${seatCode}</span>")
                    } else {
                        sb.append("<a href=\"/randseat/seat/show/${seatId}\" style='height:80px;width:80px' class='btn btn-gray btn-mini btn-block disabled btn-app no-radius' data-original-title='不可用' data-rel='tooltip' data-placement='right'>")
                        sb.append("<span class=\"badge badge-yellow\">不可用</span>")
                    }
                    sb.append("</button>")
                }
                sb.append("</td>")
            }
            sb.append("</tr>")
        }
        sb.append("</table>")

        [roomInstance: roomInstance,seatMap: sb.toString()]
    }

}

grails-app/views/room/_form.gsp
<%@ page import="randseat.Room" %>



<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'name', 'error')} required">
    <label for="name">
        <g:message code="room.name.label" default="Name"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="name" required="" value="${roomInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'place', 'error')} required">
    <label for="place">
        <g:message code="room.place.label" default="Place"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="place" required="" value="${roomInstance?.place}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'code', 'error')} required">
    <label for="code">
        <g:message code="room.code.label" default="Code"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="code" required="" value="${roomInstance?.code}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'seatCount', 'error')} required">
    <label for="seatCount">
        <g:message code="room.seatCount.label" default="Seat Count"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="seatCount" type="number" value="${roomInstance.seatCount}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'width', 'error')} required">
    <label for="width">
        <g:message code="room.width.label" default="Width"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="width" type="number" value="${roomInstance.width}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'height', 'error')} required">
    <label for="height">
        <g:message code="room.height.label" default="Height"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="height" type="number" value="${roomInstance.height}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'ranges', 'error')} ">
    <label for="ranges">
        <g:message code="room.ranges.label" default="Ranges"/>
        
    </label>
    
<ul class="one-to-many">
<g:each in="${roomInstance?.ranges?}" var="r">
    <li><g:link controller="ranges" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="ranges" action="create" params="['room.id': roomInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'ranges.label', default: 'Ranges')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'exams', 'error')} ">
    <label for="exams">
        <g:message code="room.exams.label" default="Exams"/>
        
    </label>
    
<ul class="one-to-many">
<g:each in="${roomInstance?.exams?}" var="e">
    <li><g:link controller="examRoom" action="show" id="${e.id}">${e?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="examRoom" action="create" params="['room.id': roomInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'examRoom.label', default: 'ExamRoom')])}</g:link>
</li>
</ul>


</div>

grails-app/views/room/create.gsp
<%@ page import="randseat.Room" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <g:link class="btn">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </g:link>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="save" >
    <fieldset>
        <f:all bean="roomInstance" except="exams,students"/>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.create.label" default="Create"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/room/edit.gsp
<%@ page import="randseat.Room" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="update" id="${roomInstance?.id}" >
    <g:hiddenField name="version" value="${roomInstance?.version}"/>
    <fieldset>
        <f:all bean="roomInstance" except="exams,students"/>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.update.label" default="Update"/>
        </ui:button>
        <ui:button type="submit" mode="danger" name="_action_delete" formnovalidate="true" id="delete-button">
            <i class="icon-trash icon-white"></i>
            <g:message code="default.button.delete.label" default="Delete"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/room/index.gsp
<%@ page import="randseat.Room" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-room" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>
            
            <g:sortableColumn property="name"
                              title="${message(code: 'room.name.label', default: 'Name')}"/>
            
            <g:sortableColumn property="place"
                              title="${message(code: 'room.place.label', default: 'Place')}"/>
            
            <g:sortableColumn property="code"
                              title="${message(code: 'room.code.label', default: 'Code')}"/>
            
            <g:sortableColumn property="seatCount"
                              title="${message(code: 'room.seatCount.label', default: 'Seat Count')}"/>
            
            <g:sortableColumn property="width"
                              title="${message(code: 'room.width.label', default: 'Width')}"/>
            
            <g:sortableColumn property="height"
                              title="${message(code: 'room.height.label', default: 'Height')}"/>
            
        </tr>
        </thead>
        <tbody>
        <g:each in="${roomInstanceList}" status="i" var="roomInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                
                <td><g:link action="show" id="${roomInstance.id}">${fieldValue(bean: roomInstance, field: "name")}</g:link></td>
                
                <td>${fieldValue(bean: roomInstance, field: "place")}</td>
                
                <td>${fieldValue(bean: roomInstance, field: "code")}</td>
                
                <td>${fieldValue(bean: roomInstance, field: "seatCount")}</td>
                
                <td>${fieldValue(bean: roomInstance, field: "width")}</td>
                
                <td>${fieldValue(bean: roomInstance, field: "height")}</td>
                
            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${roomInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/room/list.gsp
<%@ page import="randseat.Room" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <g:link action="create" class="btn btn-primary">
            <g:message code="default.button.create.label" default="Create"/>
        </g:link>
    </theme:zone>
    <ui:displayMessage/>
    <div id="flip-scroll">
        <ui:table class="table-bordered table-hover">
            <thead>
            <ui:tr>
                
                <g:sortableColumn property="id"
                                  title="${message(code: 'room.id.label', default: 'Id')}" params="${params}"/>
                
                <g:sortableColumn property="name"
                                  title="${message(code: 'room.name.label', default: 'Name')}" params="${params}"/>
                
                <g:sortableColumn property="place"
                                  title="${message(code: 'room.place.label', default: 'Place')}" params="${params}"/>
                
                <g:sortableColumn property="code"
                                  title="${message(code: 'room.code.label', default: 'Code')}" params="${params}"/>
                
                <g:sortableColumn property="seatCount"
                                  title="${message(code: 'room.seatCount.label', default: 'Seat Count')}" params="${params}"/>
                
                <g:sortableColumn property="width"
                                  title="${message(code: 'room.width.label', default: 'Width')}" params="${params}"/>
                
                <g:sortableColumn property="height"
                                  title="${message(code: 'room.height.label', default: 'Height')}" params="${params}"/>
                
                <th><g:message code="default.actions.label" default="Actions"/></th>
            </ui:tr>
            </thead>
            <tbody>
            <g:each in="${roomInstanceList}" var="roomInstance">
                <ui:tr>
                    
                    <td><f:display bean="${roomInstance}" property="id"/></td>
                    
                    <td><f:display bean="${roomInstance}" property="name"/></td>
                    
                    <td><f:display bean="${roomInstance}" property="place"/></td>
                    
                    <td><f:display bean="${roomInstance}" property="code"/></td>
                    
                    <td><f:display bean="${roomInstance}" property="seatCount"/></td>
                    
                    <td><f:display bean="${roomInstance}" property="width"/></td>
                    
                    <td><f:display bean="${roomInstance}" property="height"/></td>
                    
                    <td class="link">
                        <ui:button kind="anchor" mode="info" class="btn-mini" action="show" id="${roomInstance.id}">
                            <i class="icon-info-sign"></i>
                            <g:message code="default.button.show.label" default="Show"/>
                        </ui:button>
                        <ui:button kind="anchor" mode="info" class="btn-mini" action="showSeatMap" id="${roomInstance.id}">
                            <i class="icon-group"></i>
                            座位图
                        </ui:button>
                    </td>
                </ui:tr>
            </g:each>
            </tbody>
        </ui:table>
    </div>

    <div class="pagination">
        <ui:paginate total="${roomInstanceTotal}" params="${params}"/>
    </div>
</theme:zone>
</body>
</html>

grails-app/views/room/show.gsp
<%@ page import="randseat.Room" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor" mode="primary" action="edit" id="${roomInstance?.id}">
            <i class="icon-pencil"></i>
            <g:message code="default.button.edit.label" default="Edit"/>
        </ui:button>
        <ui:button kind="anchor" mode="primary" action="showSeatMap" id="${roomInstance?.id}">
            座位图
        </ui:button>
        <ui:form action="delete" class="inline">
            <g:hiddenField name="id" value="${roomInstance?.id}"/>
            <ui:button mode="danger" type="submit" name="_action_delete" id="delete-button">
                <i class="icon-trash icon-white"></i>
                <g:message code="default.button.delete.label" default="Delete"/>
            </ui:button>
        </ui:form>
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <dl>
        
        <g:if test="${roomInstance?.name}">
            <dt><g:message code="room.name.label" default="Name"/></dt>
            
            <dd><f:display bean="${roomInstance}" property="name"/></dd>
            
        </g:if>
        
        <g:if test="${roomInstance?.place}">
            <dt><g:message code="room.place.label" default="Place"/></dt>
            
            <dd><f:display bean="${roomInstance}" property="place"/></dd>
            
        </g:if>
        
        <g:if test="${roomInstance?.code}">
            <dt><g:message code="room.code.label" default="Code"/></dt>
            
            <dd><f:display bean="${roomInstance}" property="code"/></dd>
            
        </g:if>
        
        <g:if test="${roomInstance?.seatCount}">
            <dt><g:message code="room.seatCount.label" default="Seat Count"/></dt>
            
            <dd><f:display bean="${roomInstance}" property="seatCount"/></dd>
            
        </g:if>
        
        <g:if test="${roomInstance?.width}">
            <dt><g:message code="room.width.label" default="Width"/></dt>
            
            <dd><f:display bean="${roomInstance}" property="width"/></dd>
            
        </g:if>
        
        <g:if test="${roomInstance?.height}">
            <dt><g:message code="room.height.label" default="Height"/></dt>
            
            <dd><f:display bean="${roomInstance}" property="height"/></dd>
            
        </g:if>
        
        <g:if test="${roomInstance?.ranges}">
            <dt><g:message code="room.ranges.label" default="Ranges"/></dt>
            
            <g:each in="${roomInstance.ranges}" var="r">
                <dd><g:link controller="ranges" action="show"
                            id="${r.id}">${r?.encodeAsHTML()}</g:link></dd>
            </g:each>
            
        </g:if>
        
        <g:if test="${roomInstance?.exams}">
            <dt><g:message code="room.exams.label" default="Exams"/></dt>
            
            <g:each in="${roomInstance.exams}" var="e">
                <dd><g:link controller="examRoom" action="show"
                            id="${e.id}">${e?.encodeAsHTML()}</g:link></dd>
            </g:each>
            
        </g:if>
        
    </dl>

</theme:zone>
</body>
</html>

grails-app/views/room/showSeatMap.gsp
<%@ page import="randseat.Room" %>
<%@ page defaultCodec="none" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}"/>
    <title>${roomInstance.name} 座位图</title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    ${seatMap}
</theme:zone>
</body>
</html>