grails-app/domain/randseat/Student.groovy
package randseat

class Student {

    String username
    String idnumber
    String firstname
    String lastname
    String password
    String email
    String department
    boolean isSorted=false

    static belongsTo = [exam: Exam,room: Room,seat: Seat,paper:Paper]

    static constraints = {
        username nullable: false
        idnumber nullable: false
        firstname nullable: false
        lastname nullable: false
        password nullable: true
        email nullable: true
        department nullable: true
        exam nullable: true
        room nullable: true
        seat nullable: true
        paper nullable: true
        isSorted nullable: false
    }

    static mapping = {
        username comment: '用户名'
        idnumber comment: '学号'
        firstname comment: '名字'
        lastname comment: '姓氏'
        password comment: '密码'
        email comment: '邮箱'
        department comment: '班级'
        exam comment: '考试'
        room comment: '考场'
        seat comment: '座位'
        paper comment: '考卷'
        isSorted comment: '是否已经排座位'
    }
}

grails-app/controllers/randseat/StudentController.groovy
package randseat

import grails.transaction.Transactional
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.jdbc.core.JdbcTemplate

class StudentController {

    def grailsUiExtensions
    def dataSource

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params['max'] = Math.min(max ?: 10, 100)
        def r = Student.createCriteria().list(params){
            if (params['exam']){
                def examInstance = Exam.findById(params.getInt('exam'))
                if (examInstance)
                    eq('exam',examInstance)
            }
        }
        [studentInstanceList: r, studentInstanceTotal: r.totalCount, params: params]
    }

    def create() {
        def examInstance = Exam.findById(params.getInt('exam'))
        if (!examInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'exam.label', default: 'Exam'), params['exam']])
            redirect(action: "list",controller: 'exam')
            return
        }
        def studentInstance = new Student()
        studentInstance.exam = examInstance
        [studentInstance: studentInstance]
    }

    /**
     * TODO 需要判断重复导入的情况
     * @return
     */
    @Transactional
    def save() {
        def examInstance = Exam.findById(params.getInt('exam'))
        if (!examInstance){
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'exam.label', default: 'Exam'), params['exam']])
            redirect(action: "list",controller: 'exam')
            return
        }

        String[] students = Student.executeQuery("select distinct idnumber from Student s where s.exam=:exam",[exam: examInstance])

        String[] itemList = params['items'].toString().trim().split("\\n")
        List<String> wrongItems = new ArrayList<String>()
        List<String> multiItems = new ArrayList<String>()
        int successCount=0,failCount=0,multiCount=0
        itemList.each { r ->
            String[] it = r.trim().split("\\s")
            List<String> itemAttr = new ArrayList<String>() //学号、姓名、班级
            for (int i=0;i<it.size();i++){
                String str = it[i].trim()
                if (str) itemAttr.add(str)
            }

            if (itemAttr.size()!=3){
                wrongItems.add(r)
                failCount++
            } else {
                // 判断是否有重复考生
                if (students.contains(itemAttr[0])){
                    multiItems.add(r)
                    multiCount++
                } else {
                    def jdbc = new JdbcTemplate(dataSource)
                    def sql = "insert into randseat.student (version,username,idnumber,firstname,lastname,password,email,department,exam_id,is_sorted) values(0,'${itemAttr[0]}','${itemAttr[0]}','${itemAttr[1]}','${itemAttr[1]}','123456','${itemAttr[0]}@no.email','${itemAttr[2]}',${examInstance.id},false)"
                    jdbc.execute(sql)
                    successCount ++
                }
            }
        }

        def message = ""
        def hasError=false
        if (failCount==0 && multiCount==0){
            message="全部导入成功"
            flash.message = message
        } else if (successCount==0){
            message="全部导入失败<br />重复导入的有：${multiItems.toString()}<br />导入失败的有：${wrongItems.toString()}"
            flash.message = message
            hasError=true
        } else {
            message="成功的有${successCount}条,导入失败的有${failCount}条,重复导入的有${multiCount}。<br />重复导入的有：${multiItems.toString()}<br />失败的有${wrongItems.toString()}"
            flash.message = message
            hasError=true
        }

        redirect(action: "show",controller: "exam", id: examInstance.id,hasError:hasError)
    }

    def show(Long id) {
        def studentInstance = Student.get(id)
        if (!studentInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'student.label', default: 'Student'), id])
            redirect(action: "list")
            return
        }

        [studentInstance: studentInstance]
    }

    def edit(Long id) {
        def studentInstance = Student.get(id)
        if (!studentInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'student.label', default: 'Student'), id])
            redirect(action: "list")
            return
        }

        [studentInstance: studentInstance]
    }

    def update(Long id, Long version) {
        def studentInstance = Student.get(id)
        if (!studentInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'student.label', default: 'Student'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (studentInstance.version > version) {
                    studentInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                            [message(code: 'student.label', default: 'Student')] as Object[],
                            "Another user has updated this Student while you were editing")
                render(view: "edit", model: [studentInstance: studentInstance])
                return
            }
        }

        bindData(studentInstance, params)

        if (!studentInstance.save(flush: true)) {
            render(view: "edit", model: [studentInstance: studentInstance])
            return
        }

        grailsUiExtensions.displayFlashMessage(text: 'default.updated.message', args: [message(code: 'student.label', default: 'Student'), studentInstance])
        redirect(action: "show", id: studentInstance.id)
    }

    def delete(Long id) {
        def studentInstance = Student.get(id)
        if (!studentInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'student.label', default: 'Student'), id])
            redirect(action: "list")
            return
        }

        try {
            studentInstance.delete(flush: true)
            grailsUiExtensions.displayFlashMessage(text: 'default.deleted.message', args: [message(code: 'student.label', default: 'Student'), studentInstance])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            grailsUiExtensions.displayFlashMessage(type: 'error', text: 'default.not.deleted.message', args: [message(code: 'student.label', default: 'Student'), studentInstance])
            redirect(action: "show", id: id)
        }
    }
}

grails-app/views/student/_form.gsp
<%@ page import="randseat.Student" %>



<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'username', 'error')} required">
    <label for="username">
        <g:message code="student.username.label" default="Username"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="username" required="" value="${studentInstance?.username}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'idnumber', 'error')} required">
    <label for="idnumber">
        <g:message code="student.idnumber.label" default="Idnumber"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="idnumber" required="" value="${studentInstance?.idnumber}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'firstname', 'error')} required">
    <label for="firstname">
        <g:message code="student.firstname.label" default="Firstname"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="firstname" required="" value="${studentInstance?.firstname}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'lastname', 'error')} required">
    <label for="lastname">
        <g:message code="student.lastname.label" default="Lastname"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="lastname" required="" value="${studentInstance?.lastname}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'password', 'error')} ">
    <label for="password">
        <g:message code="student.password.label" default="Password"/>
        
    </label>
    <g:textField name="password" value="${studentInstance?.password}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'email', 'error')} ">
    <label for="email">
        <g:message code="student.email.label" default="Email"/>
        
    </label>
    <g:textField name="email" value="${studentInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'department', 'error')} ">
    <label for="department">
        <g:message code="student.department.label" default="Department"/>
        
    </label>
    <g:textField name="department" value="${studentInstance?.department}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'exam', 'error')} ">
    <label for="exam">
        <g:message code="student.exam.label" default="Exam"/>
        
    </label>
    <g:select id="exam" name="exam.id" from="${randseat.Exam.list()}" optionKey="id" value="${studentInstance?.exam?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'room', 'error')} ">
    <label for="room">
        <g:message code="student.room.label" default="Room"/>
        
    </label>
    <g:select id="room" name="room.id" from="${randseat.Room.list()}" optionKey="id" value="${studentInstance?.room?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'seat', 'error')} ">
    <label for="seat">
        <g:message code="student.seat.label" default="Seat"/>
        
    </label>
    <g:select id="seat" name="seat.id" from="${randseat.Seat.list()}" optionKey="id" value="${studentInstance?.seat?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'paper', 'error')} ">
    <label for="paper">
        <g:message code="student.paper.label" default="Paper"/>
        
    </label>
    <g:select id="paper" name="paper.id" from="${randseat.Paper.list()}" optionKey="id" value="${studentInstance?.paper?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

grails-app/views/student/create.gsp
<%@ page import="randseat.Student" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <g:link class="btn">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </g:link>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="save" >
    <fieldset>
        %{--<f:all bean="studentInstance"/>--}%
        <input class="hidden" id="exam" name="exam" value="${studentInstance?.exam.id}"/>
        <div class="widget-box">
            <div class="widget-header">
                <h5>导入数据</h5>
            </div>

            <div class="widget-body">
                <div class="widget-main">

                    <p>将表格复制粘贴到文本框，分别是：学号、姓名、班级，以空格或者TAB键隔开，行与行之间用回车隔开。</p>
                    <p>可直接从Excel表格中选中相关区域进行复制粘贴。</p>
                    <hr>
                    <g:textArea name="items" class="span12" value="${params.get('items')}" style="margin: 0px; height: 400px;" required="required"/>
                </div>
            </div>
        </div>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.create.label" default="Create"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/student/edit.gsp
<%@ page import="randseat.Student" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="update" id="${studentInstance?.id}" >
    <g:hiddenField name="version" value="${studentInstance?.version}"/>
    <fieldset>
        <f:all bean="studentInstance"/>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.update.label" default="Update"/>
        </ui:button>
        <ui:button type="submit" mode="danger" name="_action_delete" formnovalidate="true" id="delete-button">
            <i class="icon-trash icon-white"></i>
            <g:message code="default.button.delete.label" default="Delete"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/student/index.gsp
<%@ page import="randseat.Student" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-student" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>
            
            <g:sortableColumn property="username"
                              title="${message(code: 'student.username.label', default: 'Username')}"/>
            
            <g:sortableColumn property="idnumber"
                              title="${message(code: 'student.idnumber.label', default: 'Idnumber')}"/>
            
            <g:sortableColumn property="firstname"
                              title="${message(code: 'student.firstname.label', default: 'Firstname')}"/>
            
            <g:sortableColumn property="lastname"
                              title="${message(code: 'student.lastname.label', default: 'Lastname')}"/>
            
            <g:sortableColumn property="password"
                              title="${message(code: 'student.password.label', default: 'Password')}"/>
            
            <g:sortableColumn property="email"
                              title="${message(code: 'student.email.label', default: 'Email')}"/>
            
        </tr>
        </thead>
        <tbody>
        <g:each in="${studentInstanceList}" status="i" var="studentInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                
                <td><g:link action="show" id="${studentInstance.id}">${fieldValue(bean: studentInstance, field: "username")}</g:link></td>
                
                <td>${fieldValue(bean: studentInstance, field: "idnumber")}</td>
                
                <td>${fieldValue(bean: studentInstance, field: "firstname")}</td>
                
                <td>${fieldValue(bean: studentInstance, field: "lastname")}</td>
                
                <td>${fieldValue(bean: studentInstance, field: "password")}</td>
                
                <td>${fieldValue(bean: studentInstance, field: "email")}</td>
                
            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${studentInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/student/list.gsp
<%@ page import="randseat.Student" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
    </theme:zone>
    <ui:displayMessage/>
    <div id="flip-scroll">
        <ui:table class="table-bordered table-hover">
            <thead>
            <ui:tr>
                
                <g:sortableColumn property="id"
                                  title="${message(code: 'student.id.label', default: 'Id')}" params="${params}"/>
                
                <g:sortableColumn property="username"
                                  title="${message(code: 'student.username.label', default: 'Username')}" params="${params}"/>
                
                <g:sortableColumn property="idnumber"
                                  title="${message(code: 'student.idnumber.label', default: 'Idnumber')}" params="${params}"/>
                
                <g:sortableColumn property="firstname"
                                  title="${message(code: 'student.firstname.label', default: 'Firstname')}" params="${params}"/>
                
                <g:sortableColumn property="lastname"
                                  title="${message(code: 'student.lastname.label', default: 'Lastname')}" params="${params}"/>
                
                <g:sortableColumn property="password"
                                  title="${message(code: 'student.password.label', default: 'Password')}" params="${params}"/>
                
                <g:sortableColumn property="email"
                                  title="${message(code: 'student.email.label', default: 'Email')}" params="${params}"/>
                
                <g:sortableColumn property="department"
                                  title="${message(code: 'student.department.label', default: 'Department')}" params="${params}"/>
                
                <th><g:message code="default.actions.label" default="Actions"/></th>
            </ui:tr>
            </thead>
            <tbody>
            <g:each in="${studentInstanceList}" var="studentInstance">
                <ui:tr>
                    
                    <td><f:display bean="${studentInstance}" property="id"/></td>
                    
                    <td><f:display bean="${studentInstance}" property="username"/></td>
                    
                    <td><f:display bean="${studentInstance}" property="idnumber"/></td>
                    
                    <td><f:display bean="${studentInstance}" property="firstname"/></td>
                    
                    <td><f:display bean="${studentInstance}" property="lastname"/></td>
                    
                    <td><f:display bean="${studentInstance}" property="password"/></td>
                    
                    <td><f:display bean="${studentInstance}" property="email"/></td>
                    
                    <td><f:display bean="${studentInstance}" property="department"/></td>
                    
                    <td class="link">
                        <ui:button kind="anchor" mode="info" class="btn-mini" action="show" id="${studentInstance.id}">
                            <i class="icon-info-sign"></i>
                            <g:message code="default.button.show.label" default="Show"/>
                        </ui:button>
                    </td>
                </ui:tr>
            </g:each>
            </tbody>
        </ui:table>
    </div>

    <div class="pagination">
        <ui:paginate total="${studentInstanceTotal}" params="${params}"/>
    </div>
</theme:zone>
</body>
</html>

grails-app/views/student/show.gsp
<%@ page import="randseat.Student" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor" mode="primary" action="edit" id="${studentInstance?.id}">
            <i class="icon-pencil"></i>
            <g:message code="default.button.edit.label" default="Edit"/>
        </ui:button>
        <ui:form action="delete" class="inline">
            <g:hiddenField name="id" value="${studentInstance?.id}"/>
            <ui:button mode="danger" type="submit" name="_action_delete" id="delete-button">
                <i class="icon-trash icon-white"></i>
                <g:message code="default.button.delete.label" default="Delete"/>
            </ui:button>
        </ui:form>
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <dl>
        
        <g:if test="${studentInstance?.username}">
            <dt><g:message code="student.username.label" default="Username"/></dt>
            
            <dd><f:display bean="${studentInstance}" property="username"/></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.idnumber}">
            <dt><g:message code="student.idnumber.label" default="Idnumber"/></dt>
            
            <dd><f:display bean="${studentInstance}" property="idnumber"/></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.firstname}">
            <dt><g:message code="student.firstname.label" default="Firstname"/></dt>
            
            <dd><f:display bean="${studentInstance}" property="firstname"/></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.lastname}">
            <dt><g:message code="student.lastname.label" default="Lastname"/></dt>
            
            <dd><f:display bean="${studentInstance}" property="lastname"/></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.password}">
            <dt><g:message code="student.password.label" default="Password"/></dt>
            
            <dd><f:display bean="${studentInstance}" property="password"/></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.email}">
            <dt><g:message code="student.email.label" default="Email"/></dt>
            
            <dd><f:display bean="${studentInstance}" property="email"/></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.department}">
            <dt><g:message code="student.department.label" default="Department"/></dt>
            
            <dd><f:display bean="${studentInstance}" property="department"/></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.exam}">
            <dt><g:message code="student.exam.label" default="Exam"/></dt>
            
            <dd><g:link controller="exam" action="show"
                        id="${studentInstance?.exam?.id}"><f:display bean="${studentInstance}"
                                                                           property="exam"/></g:link></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.room}">
            <dt><g:message code="student.room.label" default="Room"/></dt>
            
            <dd><g:link controller="room" action="show"
                        id="${studentInstance?.room?.id}"><f:display bean="${studentInstance}"
                                                                           property="room"/></g:link></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.seat}">
            <dt><g:message code="student.seat.label" default="Seat"/></dt>
            
            <dd><g:link controller="seat" action="show"
                        id="${studentInstance?.seat?.id}"><f:display bean="${studentInstance}"
                                                                           property="seat"/></g:link></dd>
            
        </g:if>
        
        <g:if test="${studentInstance?.paper}">
            <dt><g:message code="student.paper.label" default="Paper"/></dt>
            
            <dd><g:link controller="paper" action="show"
                        id="${studentInstance?.paper?.id}"><f:display bean="${studentInstance}"
                                                                           property="paper"/></g:link></dd>
            
        </g:if>
        
    </dl>

</theme:zone>
</body>
</html>