grails-app/domain/randseat/Seat.groovy
package randseat

class Seat {

    Integer code
    Integer row
    Integer col
    boolean usable=true

    static belongsTo = [range: Ranges]

    static hasMany = [students:Student]

    static constraints = {
        code nullable: false
        row nullable: false
        col nullable: false
        students nullable: true
        usable nullable: false
    }

    static mapping = {
        code comment: '座位编号'
        row comment: '座位横向坐标'
        col comment: '座位纵向坐标'
        usable comment: '是否可用'
        students comment: '该座位的学生'
    }

    @Override
    public String toString() {
        return "Seat{" + range + code + '}'
    }

    Student getStudent(Exam exam){
        return Student.findByExamAndSeat(exam,this)
    }
}

grails-app/controllers/randseat/SeatController.groovy
package randseat

import org.springframework.dao.DataIntegrityViolationException

class SeatController {

    def grailsUiExtensions

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params['max'] = Math.min(max ?: 10, 100)
        [seatInstanceList: Seat.list(params), seatInstanceTotal: Seat.count(), params: params]
    }

    def create() {
        [seatInstance: new Seat(params)]
    }

    def save() {
        def seatInstance = new Seat(params)
        if (!seatInstance.save(flush: true)) {
            render(view: "create", model: [seatInstance: seatInstance])
            return
        }

        grailsUiExtensions.displayFlashMessage(text: 'default.created.message', args: [message(code: 'seat.label', default: 'Seat'), seatInstance])
        redirect(action: "show", id: seatInstance.id)
    }

    def show(Long id) {
        def seatInstance = Seat.get(id)
        if (!seatInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'seat.label', default: 'Seat'), id])
            redirect(action: "list")
            return
        }

        [seatInstance: seatInstance]
    }

    def edit(Long id) {
        def seatInstance = Seat.get(id)
        if (!seatInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'seat.label', default: 'Seat'), id])
            redirect(action: "list")
            return
        }

        [seatInstance: seatInstance]
    }

    def update(Long id, Long version) {
        def seatInstance = Seat.get(id)
        if (!seatInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'seat.label', default: 'Seat'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (seatInstance.version > version) {
                    seatInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                            [message(code: 'seat.label', default: 'Seat')] as Object[],
                            "Another user has updated this Seat while you were editing")
                render(view: "edit", model: [seatInstance: seatInstance])
                return
            }
        }

        bindData(seatInstance, params)

        if (!seatInstance.save(flush: true)) {
            render(view: "edit", model: [seatInstance: seatInstance])
            return
        }

        grailsUiExtensions.displayFlashMessage(text: 'default.updated.message', args: [message(code: 'seat.label', default: 'Seat'), seatInstance])
        redirect(action: "show", id: seatInstance.id)
    }

    def delete(Long id) {
        def seatInstance = Seat.get(id)
        if (!seatInstance) {
            grailsUiExtensions.displayFlashMessage(type: 'warning', text: 'default.not.found.message', args: [message(code: 'seat.label', default: 'Seat'), id])
            redirect(action: "list")
            return
        }

        try {
            seatInstance.delete(flush: true)
            grailsUiExtensions.displayFlashMessage(text: 'default.deleted.message', args: [message(code: 'seat.label', default: 'Seat'), seatInstance])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            grailsUiExtensions.displayFlashMessage(type: 'error', text: 'default.not.deleted.message', args: [message(code: 'seat.label', default: 'Seat'), seatInstance])
            redirect(action: "show", id: id)
        }
    }
/*
    def updateCol() {
        def seatInstanceList = Seat.all
        seatInstanceList.each {seat ->
            def newcol = seat.range.room.width - seat.col + 1
            seat.col = newcol
        }

        Seat.saveAll(seatInstanceList)
    }
*/
}

grails-app/views/seat/_form.gsp
<%@ page import="randseat.Seat" %>



<div class="fieldcontain ${hasErrors(bean: seatInstance, field: 'code', 'error')} required">
    <label for="code">
        <g:message code="seat.code.label" default="Code"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="code" type="number" value="${seatInstance.code}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: seatInstance, field: 'row', 'error')} required">
    <label for="row">
        <g:message code="seat.row.label" default="Row"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="row" type="number" value="${seatInstance.row}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: seatInstance, field: 'col', 'error')} required">
    <label for="col">
        <g:message code="seat.col.label" default="Col"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="col" type="number" value="${seatInstance.col}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: seatInstance, field: 'usable', 'error')} ">
    <label for="usable">
        <g:message code="seat.usable.label" default="Usable"/>
        
    </label>
    <g:checkBox name="usable" value="${seatInstance?.usable}" />

</div>

<div class="fieldcontain ${hasErrors(bean: seatInstance, field: 'range', 'error')} required">
    <label for="range">
        <g:message code="seat.range.label" default="Range"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="range" name="range.id" from="${randseat.Ranges.list()}" optionKey="id" required="" value="${seatInstance?.range?.id}" class="many-to-one"/>

</div>

grails-app/views/seat/create.gsp
<%@ page import="randseat.Seat" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'seat.label', default: 'Seat')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <g:link class="btn">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </g:link>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="save" >
    <fieldset>
        <f:all bean="seatInstance" except="students"/>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.create.label" default="Create"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/seat/edit.gsp
<%@ page import="randseat.Seat" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'seat.label', default: 'Seat')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <ui:form action="update" id="${seatInstance?.id}" >
    <g:hiddenField name="version" value="${seatInstance?.version}"/>
    <fieldset>
        <f:all bean="seatInstance" except="students"/>
    </fieldset>
    <ui:actions>
        <ui:button type="submit" mode="primary">
            <i class="icon-ok icon-white"></i>
            <g:message code="default.button.update.label" default="Update"/>
        </ui:button>
        <ui:button type="submit" mode="danger" name="_action_delete" formnovalidate="true" id="delete-button">
            <i class="icon-trash icon-white"></i>
            <g:message code="default.button.delete.label" default="Delete"/>
        </ui:button>
    </ui:actions>
</ui:form>
</theme:zone>
</body>
</html>

grails-app/views/seat/index.gsp
<%@ page import="randseat.Seat" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'seat.label', default: 'Seat')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-seat" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-seat" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>
            
            <g:sortableColumn property="code"
                              title="${message(code: 'seat.code.label', default: 'Code')}"/>
            
            <g:sortableColumn property="row"
                              title="${message(code: 'seat.row.label', default: 'Row')}"/>
            
            <g:sortableColumn property="col"
                              title="${message(code: 'seat.col.label', default: 'Col')}"/>
            
            <g:sortableColumn property="usable"
                              title="${message(code: 'seat.usable.label', default: 'Usable')}"/>
            
            <th><g:message code="seat.range.label" default="Range"/></th>
            
        </tr>
        </thead>
        <tbody>
        <g:each in="${seatInstanceList}" status="i" var="seatInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                
                <td><g:link action="show" id="${seatInstance.id}">${fieldValue(bean: seatInstance, field: "code")}</g:link></td>
                
                <td>${fieldValue(bean: seatInstance, field: "row")}</td>
                
                <td>${fieldValue(bean: seatInstance, field: "col")}</td>
                
                <td><g:formatBoolean boolean="${seatInstance.usable}"/></td>
                
                <td>${fieldValue(bean: seatInstance, field: "range")}</td>
                
            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${seatInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/seat/list.gsp
<%@ page import="randseat.Seat" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'seat.label', default: 'Seat')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <g:link action="create" class="btn btn-primary">
            <g:message code="default.button.create.label" default="Create"/>
        </g:link>
    </theme:zone>
    <ui:displayMessage/>
    <div id="flip-scroll">
        <ui:table class="table-bordered table-hover">
            <thead>
            <ui:tr>
                
                <g:sortableColumn property="id"
                                  title="${message(code: 'seat.id.label', default: 'Id')}" params="${params}"/>
                
                <g:sortableColumn property="code"
                                  title="${message(code: 'seat.code.label', default: 'Code')}" params="${params}"/>
                
                <g:sortableColumn property="row"
                                  title="${message(code: 'seat.row.label', default: 'Row')}" params="${params}"/>
                
                <g:sortableColumn property="col"
                                  title="${message(code: 'seat.col.label', default: 'Col')}" params="${params}"/>
                
                <g:sortableColumn property="usable"
                                  title="${message(code: 'seat.usable.label', default: 'Usable')}" params="${params}"/>
                
                <th><g:message code="seat.range.label" default="Range"/></th>
                
                <th><g:message code="default.actions.label" default="Actions"/></th>
            </ui:tr>
            </thead>
            <tbody>
            <g:each in="${seatInstanceList}" var="seatInstance">
                <ui:tr>
                    
                    <td><f:display bean="${seatInstance}" property="id"/></td>
                    
                    <td><f:display bean="${seatInstance}" property="code"/></td>
                    
                    <td><f:display bean="${seatInstance}" property="row"/></td>
                    
                    <td><f:display bean="${seatInstance}" property="col"/></td>
                    
                    <td><g:formatBoolean boolean="${seatInstance.usable}"/></td>
                    
                    <td><f:display bean="${seatInstance}" property="range"/></td>
                    
                    <td class="link">
                        <ui:button kind="anchor" mode="info" class="btn-mini" action="show" id="${seatInstance.id}">
                            <i class="icon-info-sign"></i>
                            <g:message code="default.button.show.label" default="Show"/>
                        </ui:button>
                    </td>
                </ui:tr>
            </g:each>
            </tbody>
        </ui:table>
    </div>

    <div class="pagination">
        <ui:paginate total="${seatInstanceTotal}" params="${params}"/>
    </div>
</theme:zone>
</body>
</html>

grails-app/views/seat/show.gsp
<%@ page import="randseat.Seat" %>
<!doctype html>
<html>
<head>
    <theme:layout name="dataentry"/>
    <g:set var="entityName" value="${message(code: 'seat.label', default: 'Seat')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
    <r:require modules="application"/>
</head>

<body>
<theme:zone name="body">
    <theme:zone name="header-actions">
        <ui:button kind="anchor" mode="primary" action="edit" id="${seatInstance?.id}">
            <i class="icon-pencil"></i>
            <g:message code="default.button.edit.label" default="Edit"/>
        </ui:button>
        <ui:form action="delete" class="inline">
            <g:hiddenField name="id" value="${seatInstance?.id}"/>
            <ui:button mode="danger" type="submit" name="_action_delete" id="delete-button">
                <i class="icon-trash icon-white"></i>
                <g:message code="default.button.delete.label" default="Delete"/>
            </ui:button>
        </ui:form>
        <ui:button kind="anchor">
            <i class="icon-arrow-left"></i>
            <g:message code="default.button.return.label" default="Return"/>
        </ui:button>
    </theme:zone>
    <ui:displayMessage/>
    <dl>
        
        <g:if test="${seatInstance?.code}">
            <dt><g:message code="seat.code.label" default="Code"/></dt>
            
            <dd><f:display bean="${seatInstance}" property="code"/></dd>
            
        </g:if>
        
        <g:if test="${seatInstance?.row}">
            <dt><g:message code="seat.row.label" default="Row"/></dt>
            
            <dd><f:display bean="${seatInstance}" property="row"/></dd>
            
        </g:if>
        
        <g:if test="${seatInstance?.col}">
            <dt><g:message code="seat.col.label" default="Col"/></dt>
            
            <dd><f:display bean="${seatInstance}" property="col"/></dd>
            
        </g:if>
        
        <g:if test="${seatInstance?.usable}">
            <dt><g:message code="seat.usable.label" default="Usable"/></dt>
            
            <dd><g:formatBoolean boolean="${seatInstance?.usable}"/></dd>
            
        </g:if>
        
        <g:if test="${seatInstance?.range}">
            <dt><g:message code="seat.range.label" default="Range"/></dt>
            
            <dd><g:link controller="ranges" action="show"
                        id="${seatInstance?.range?.id}"><f:display bean="${seatInstance}"
                                                                           property="range"/></g:link></dd>
            
        </g:if>
        
    </dl>

</theme:zone>
</body>
</html>